unpackaged/objects/Buy__c.object
<CustomObject>
    <fields>
        <fullName>CashRegister__c</fullName>
        <label>Cash Register</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>Date And Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Responsible Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Buys</relationshipLabel>
        <relationshipName>Buys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Buy</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/BuyProductJunction__c.object
<CustomObject>
    <fields>
        <fullName>Buy__c</fullName>
        <label>Buy</label>
        <referenceTo>Buy__c</referenceTo>
        <relationshipLabel>Buy Product Junctions</relationshipLabel>
        <relationshipName>Buy_Product_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Buy Product Junctions</relationshipLabel>
        <relationshipName>Buy_Product_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Buy Product Junction</label>
    <nameField>
        <displayFormat>BP-{0000000000}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buy Product Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>QuantityType__c</fullName>
        <label>Quantity Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>liter</fullName>
                </value>
                <value>
                    <fullName>cubic-meter</fullName>
                </value>
                <value>
                    <fullName>meter</fullName>
                </value>
                <value>
                    <fullName>unit</fullName>
                </value>
                <value>
                    <fullName>kilogram</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RetailPrice__c</fullName>
        <formula>BasePrice__c * (1 + IF(CustomMargin__c &lt;&gt; 0, CustomMargin__c, 0.2) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retail Price</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ProductsController.cls
/**
 * Created by ROHIRYM on 10/26/17.
 */
public class ProductsController {

    public Product__c searchProd {get;set;}
    public List<Product__c> allFoundProducts {get;set;}
    
    public Id productId {get;set;}
    public Product__c product {get;set;}
    public List<BuyProductJunctionWrapper> buyProductJunctionsWrappers {get;set;}
    
    public Double allSum {get;set;}
    public String employeeId {get;set;}
    
    public ProductsController() {
        searchProd = new Product__c();
        buyProductJunctionsWrappers = new List<BuyProductJunctionWrapper>();
        allSum = 0;
    }
    
    public void findAllProducts() {
        String searchName = '%'+(searchProd.Name == null ? '' : searchProd.Name)+'%';
        allFoundProducts = [SELECT Id, Name, QuantityType__c, RetailPrice__c FROM Product__c WHERE Name LIKE :searchName LIMIT 10];
    }
    
    public void addNewBuyProductJunction() {
        product = [SELECT Id, Name, QuantityType__c, RetailPrice__c FROM Product__c WHERE Id = :productId LIMIT 1];
        for (BuyProductJunctionWrapper bpjw : buyProductJunctionsWrappers) {
            if (bpjw.product.Id == product.Id) {
                bpjw.buyProductJunction.Quantity__c = bpjw.buyProductJunction.Quantity__c + 1;
                bpjw.sum = bpjw.buyProductJunction.Quantity__c * bpjw.product.RetailPrice__c;
                refreshAllSum();
                return;
            }
        }
        BuyProductJunctionWrapper junc = new BuyProductJunctionWrapper();
        junc.product = product;
        junc.buyProductJunction = new BuyProductJunction__c(Product__c = product.Id, Quantity__c = 1);
        junc.sum = junc.buyProductJunction.Quantity__c * junc.product.RetailPrice__c;
        buyProductJunctionsWrappers.add(junc);
        refreshAllSum();
    }
    
    public void refreshSums() {
        for (BuyProductJunctionWrapper bpjw : buyProductJunctionsWrappers) {
            bpjw.sum = bpjw.buyProductJunction.Quantity__c * bpjw.product.RetailPrice__c;
        }
        refreshAllSum();
    }
    
    public void refreshAllSum() {
        allSum = 0;
        for (BuyProductJunctionWrapper bpjw : buyProductJunctionsWrappers) {
            allSum = allSum + bpjw.sum;
        }
    }
    
    public void deleteBuyProductJunction() {
        Integer index = 0;
        for (BuyProductJunctionWrapper bpjw : buyProductJunctionsWrappers) {
            if (bpjw.product.Id == productId) {
                break;
            }
            index++;
        }
        if (index < buyProductJunctionsWrappers.size()) {
            buyProductJunctionsWrappers.remove(index);
        }
        refreshAllSum();
    }
    
    public List<SelectOption> getdynamiclist() {
        List<SelectOption> options = new List<SelectOption>();
        List<Employee__c> employees = [SELECT Id, FirstName__c, LastName__c FROM Employee__c];
        for (Employee__c emp : employees) {
            options.add(new SelectOption(emp.Id, emp.FirstName__c + ' ' + emp.LastName__c));
        }
        return options;
    }
    
    public void saveOrder() {
        try {
            Buy__c buy = new Buy__c(CashRegister__c = 1, DateTime__c = DateTime.now(), Employee__c = employeeId);
            insert buy;
            List<BuyProductJunction__c> juncs = new List<BuyProductJunction__c>();
            for (BuyProductJunctionWrapper bpjw : buyProductJunctionsWrappers) {
                bpjw.buyProductJunction.Buy__c = buy.Id;
                juncs.add(bpjw.buyProductJunction);
            }
            insert juncs;
            buyProductJunctionsWrappers = new List<BuyProductJunctionWrapper>();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, 'Success!'));
        } catch (Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, ex.getMessage()));
        }
    }
    
    public class BuyProductJunctionWrapper {
        public Product__c product {get;set;}
        public BuyProductJunction__c buyProductJunction {get;set;}
        public Double sum {get;set;}
    }

}