unpackaged/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>TradingPoint__c</fullName>
        <label>Trading Point</label>
        <referenceTo>TradingPoint__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>CustomMargin__c</fullName>
        <label>Custom Margin</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Product_ProductType_Junction__c.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <referenceTo>ProductType__c</referenceTo>
        <relationshipLabel>Product Types Junctions</relationshipLabel>
        <relationshipName>Product_Types_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Types Junctions</relationshipLabel>
        <relationshipName>Product_Types_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Product Type Junction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Product Type Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Types Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/ProductType__c.object
<CustomObject>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>6</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>Product Type</label>
    <nameField>
        <label>Product Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/TradingPoint__c.object
<CustomObject>
    <label>Trading Point</label>
    <nameField>
        <label>Trading Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trading Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TriggerHandlerHelper.cls
public class TriggerHandlerHelper {

	public static void addTradingPoint(List<sObject> items) {
		Set<Id> employeesIds = new Set<Id>();
		for (sObject so : items) {
			employeesIds.add((Id)so.get('Employee__c'));
		}

		Map<Id, Employee__c> employeesMap = new Map<Id, Employee__c>([SELECT Id, TradingPoint__c FROM Employee__c WHERE Id IN :employeesIds]);
		for (sObject so : items) {
			so.put('TradingPoint__c', employeesMap.get((Id)so.get('Employee__c')).TradingPoint__c);
		}
	}

	public static void updateProductsCustomMargin(List<Product__c> products) {
		for (Product__c p : products) {
			List<Product_ProductType_Junction__c> tmpJuncs = p.Product_Types_Junctions__r;
			Integer cnt = 0;
			Decimal customMarginTmp = 0;
			for (Product_ProductType_Junction__c pj : tmpJuncs) {
				customMarginTmp += pj.ProductType__r.Margin__c;
				cnt ++;
			}
			p.CustomMargin__c = cnt > 0 ? customMarginTmp/cnt : 0;
		}
		update products;
	}
	//
}